name: someone_talking
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5+1
  mask_text_input_formatter: ^2.9.0
  http: ^1.6.0
  shared_preferences: ^2.1.1
  jwt_decoder: ^2.0.1
  image_picker: ^1.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/someone_talking_icon.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/someone_talking_logo.png
